// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXKjpBC1gOgxwqQ-9KXNs8dMpHdWZzmBk',
    appId: '1:584081190332:web:f2f5927f885aeac1bc4fb9',
    messagingSenderId: '584081190332',
    projectId: 'logasdos',
    authDomain: 'logasdos.firebaseapp.com',
    storageBucket: 'logasdos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDXRLQANzr0mQwqaReWtDCZcN3qD2luDc',
    appId: '1:584081190332:android:40fb019f4e2e114fbc4fb9',
    messagingSenderId: '584081190332',
    projectId: 'logasdos',
    storageBucket: 'logasdos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUiedCP8tX-q_sl8lxVzX6e1pkC50yOdM',
    appId: '1:584081190332:ios:cffbf4d5c251cf33bc4fb9',
    messagingSenderId: '584081190332',
    projectId: 'logasdos',
    storageBucket: 'logasdos.firebasestorage.app',
    iosBundleId: 'com.example.logasdos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUiedCP8tX-q_sl8lxVzX6e1pkC50yOdM',
    appId: '1:584081190332:ios:cffbf4d5c251cf33bc4fb9',
    messagingSenderId: '584081190332',
    projectId: 'logasdos',
    storageBucket: 'logasdos.firebasestorage.app',
    iosBundleId: 'com.example.logasdos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXKjpBC1gOgxwqQ-9KXNs8dMpHdWZzmBk',
    appId: '1:584081190332:web:48d2bff9f4ecd012bc4fb9',
    messagingSenderId: '584081190332',
    projectId: 'logasdos',
    authDomain: 'logasdos.firebaseapp.com',
    storageBucket: 'logasdos.firebasestorage.app',
  );
}
