// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeiTWw5hQnSbWQQaSOpHtTb15UX3mF40A',
    appId: '1:928353775326:web:9f8e96b76ce19e5a0fdc4f',
    messagingSenderId: '928353775326',
    projectId: 'relational-dbs',
    authDomain: 'relational-dbs.firebaseapp.com',
    storageBucket: 'relational-dbs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCssjHhhGQyKWPe07rJOmkQaLf3mT8QHho',
    appId: '1:928353775326:android:06d84d8e0c2c2f3c0fdc4f',
    messagingSenderId: '928353775326',
    projectId: 'relational-dbs',
    storageBucket: 'relational-dbs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpRVp4BffQ1FGZerh1zSXaCOhauvkKNQc',
    appId: '1:928353775326:ios:ec0685241be69db90fdc4f',
    messagingSenderId: '928353775326',
    projectId: 'relational-dbs',
    storageBucket: 'relational-dbs.firebasestorage.app',
    iosBundleId: 'com.example.relationalDbs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpRVp4BffQ1FGZerh1zSXaCOhauvkKNQc',
    appId: '1:928353775326:ios:ec0685241be69db90fdc4f',
    messagingSenderId: '928353775326',
    projectId: 'relational-dbs',
    storageBucket: 'relational-dbs.firebasestorage.app',
    iosBundleId: 'com.example.relationalDbs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeiTWw5hQnSbWQQaSOpHtTb15UX3mF40A',
    appId: '1:928353775326:web:008c09b18bac8a980fdc4f',
    messagingSenderId: '928353775326',
    projectId: 'relational-dbs',
    authDomain: 'relational-dbs.firebaseapp.com',
    storageBucket: 'relational-dbs.firebasestorage.app',
  );

}