// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCusvc4pAr2capOeirrbioNMUrg37SAzME',
    appId: '1:622791394356:web:027ac4b7b5b4208d953661',
    messagingSenderId: '622791394356',
    projectId: 'flutter-notes-app-a3fad',
    authDomain: 'flutter-notes-app-a3fad.firebaseapp.com',
    storageBucket: 'flutter-notes-app-a3fad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaoI4NFKMFe-9s5l3j6SCJR5c_8s8OzlI',
    appId: '1:622791394356:android:6a567f57037b1933953661',
    messagingSenderId: '622791394356',
    projectId: 'flutter-notes-app-a3fad',
    storageBucket: 'flutter-notes-app-a3fad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFSiCHcY2djUbLRApk1QyFOlAvFsBiQc0',
    appId: '1:622791394356:ios:5740c701f16bb89a953661',
    messagingSenderId: '622791394356',
    projectId: 'flutter-notes-app-a3fad',
    storageBucket: 'flutter-notes-app-a3fad.firebasestorage.app',
    iosBundleId: 'com.example.crudProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFSiCHcY2djUbLRApk1QyFOlAvFsBiQc0',
    appId: '1:622791394356:ios:5740c701f16bb89a953661',
    messagingSenderId: '622791394356',
    projectId: 'flutter-notes-app-a3fad',
    storageBucket: 'flutter-notes-app-a3fad.firebasestorage.app',
    iosBundleId: 'com.example.crudProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCusvc4pAr2capOeirrbioNMUrg37SAzME',
    appId: '1:622791394356:web:836af2ef42fbcae2953661',
    messagingSenderId: '622791394356',
    projectId: 'flutter-notes-app-a3fad',
    authDomain: 'flutter-notes-app-a3fad.firebaseapp.com',
    storageBucket: 'flutter-notes-app-a3fad.firebasestorage.app',
  );
}
