// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA77nmtMCvjdbHvT4v6Y0NJDHsg2iJPqJI',
    appId: '1:344854462997:web:c39403860510e3c897c41c',
    messagingSenderId: '344854462997',
    projectId: 'auth-modul-23b8d',
    authDomain: 'auth-modul-23b8d.firebaseapp.com',
    storageBucket: 'auth-modul-23b8d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBViCaa75x7GfvWpxz08xGE6K09n4TPFBk',
    appId: '1:344854462997:android:09e0773aa4fd268a97c41c',
    messagingSenderId: '344854462997',
    projectId: 'auth-modul-23b8d',
    storageBucket: 'auth-modul-23b8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKNoUV0dGmQLgZvCuAmCdNdWdtGu1eYzE',
    appId: '1:344854462997:ios:dd49bb97d5e487e497c41c',
    messagingSenderId: '344854462997',
    projectId: 'auth-modul-23b8d',
    storageBucket: 'auth-modul-23b8d.firebasestorage.app',
    iosBundleId: 'com.example.modulAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKNoUV0dGmQLgZvCuAmCdNdWdtGu1eYzE',
    appId: '1:344854462997:ios:dd49bb97d5e487e497c41c',
    messagingSenderId: '344854462997',
    projectId: 'auth-modul-23b8d',
    storageBucket: 'auth-modul-23b8d.firebasestorage.app',
    iosBundleId: 'com.example.modulAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA77nmtMCvjdbHvT4v6Y0NJDHsg2iJPqJI',
    appId: '1:344854462997:web:5652300edd46fa5197c41c',
    messagingSenderId: '344854462997',
    projectId: 'auth-modul-23b8d',
    authDomain: 'auth-modul-23b8d.firebaseapp.com',
    storageBucket: 'auth-modul-23b8d.firebasestorage.app',
  );

}